name: Send links to Telegram group

on:
  workflow_dispatch:

jobs:
  send-links:
    runs-on: ubuntu-latest
    steps:
      - name: Get links from list URL
        run: |
          links=$(curl -s "$LIST_URL" | jq -r '.[]')
          echo "LINKS=$links" >> $GITHUB_ENV

      - name: Send links to Telegram group
        run: |
          for link in $LINKS; do
            curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
              -d "chat_id=$GROUP_ID" \
              -d "text=$link" \
              -d "parse_mode=Markdown"
            sleep 20
          done
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          LIST_URL: ${{ secrets.LIST_URL }}
