name: Send Telegram Message Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Send message to Telegram group
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "OK !"
