name: Send Message to Telegram

on:
  schedule:
    - cron: '0 * * * *'  # This cron job runs at the top of every hour

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "OK !"
