name: Run every 5 hours

on:
  schedule:
    - cron: '0 */5 * * *' # Runs every 5 hours

jobs:
  run-every-5-hours:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your script or command
        run: |
          # Add your script or command to run here
          echo "Running every 5 hours"
